learning_rate: 0.0001
n_steps: 2048
batch_size: 64
n_epochs: 10
gamma: 0.99
gae_lambda: 0.953
clip_range: 0.2
ent_coef: 0.02
vf_coef: 0.5
max_grad_norm: 0.5
tensorboard_log: "tb_logs"
timesteps_per_stage: [100000, 400000, 600000]
