amcl:
  ros__parameters:
    use_sim_time: true
    use_map_topic: true
    min_particles: 500
    max_particles: 2000
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    laser_min_range: 0.0
    laser_max_range: 3.5
    laser_max_beams: 60
    odom_frame_id: "odom"
    odom_model_type: "diff"
    update_min_d: 0.25
    update_min_a: 0.2
    resample_interval: 1
    transform_tolerance: 1.0
    scan_topic: scan
    set_initial_pose: true

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "/home/ROS/ros_ws/src/nav2_baseline/maps/map_maze.yaml"

map_saver:
  ros__parameters:
    use_sim_time: true
    save_map_timeout: 5.0

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: true
      allow_unknown: true

controller_server:
  ros__parameters:
    use_sim_time: true
    # use_realtime_priority: false
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      debug_trajectory_details: true
      min_vel_x: 0.0
      max_vel_x: 0.22
      min_vel_y: 0.0
      max_vel_theta: 2.75
      min_speed_xy: 0.0
      max_speed_xy: 0.22
      acc_lim_x: 2.5
      acc_lim_theta: 3.2
      decel_lim_x: -2.5
      decel_lim_theta: -3.2
      vx_samples: 20
      vy_samples: 0
      vtheta_samples: 40
      sim_time: 1.5
      linear_granularity: 0.05
      angular_granularity: 0.025
      critics: ["ObstacleFootprintCritic", "PathAlignCritic", "GoalAlignCritic"]
      ObstacleFootprint.scale: 0.01
      PathAlign.scale: 32.0
      GoalAlign.scale: 24.0

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: odom
      robot_base_frame: base_footprint
      update_frequency: 5.0
      publish_frequency: 2.0
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]
      obstacle_layer:
        enabled: true
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: scan
          data_type: LaserScan
          # max_obstacle_height: 2.0
          clearing: true
          marking: true
          obstacle_range: 2.5
          raytrace_range: 3.0
      inflation_layer:
        enabled: true
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.25
        cost_scaling_factor: 3.0

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      global_frame: map
      robot_base_frame: base_footprint
      update_frequency: 1.0
      publish_frequency: 1.0
      width: 30
      height: 30
      resolution: 0.05
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        observation_sources: scan
        scan:
          topic: scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.35
        cost_scaling_factor: 3.0

behavior_server:
  ros__parameters:
    use_sim_time: true

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

waypoint_follower:
  ros__parameters:
    use_sim_time: true
